package provider

import (
	"fmt"

	"github.com/opencode-ai/opencode/internal/message"
)

// GORILLA OVERRIDE (2026-08-23): drop the content of tool results that have gone
// stale with age, not just ones a later identical call superseded.
//
// WHY THIS EXISTS ALONGSIDE supersede.go. Supersession only fires when the same
// tool ran twice with byte-identical arguments. That is the narrow case. The
// common one is a result read ONCE, early, and then carried for the rest of the
// session at full price on every single turn. The owner's framing, which is the
// design: "A diagnostic is useful until it is fixed." After that it is a
// snapshot of a world that has moved on, and it is still being uploaded.
//
// Measured 2026-08-23: over seven prompts one session went 10K -> 58K, almost
// entirely accumulated tool results. A `find .` run at 12:52 was still being
// paid for at 13:07.
//
// THE DIFFERENCE THAT MATTERS, AND THE RISK IT CARRIES. Supersession is free:
// it only ever removes a copy when a newer copy of the same thing is present
// further down. Age eviction is NOT free, because it can drop the only copy the
// model has. That is the whole reason the rules below are conservative, and why
// the stub is worded the way it is.
//
// The trade, in tokens: a result of R tokens with N turns left to run costs R*N
// to keep. Re-reading it costs R once, plus a turn, and only if the model
// actually needs it again. Past a couple of turns, evicting wins whenever the
// content is not needed, and roughly breaks even when it is. What must not
// happen is the model NOT KNOWING something was removed, because a model that
// cannot see a gap fills it from memory. So the stub names the tool, says
// plainly that the content was dropped, and tells it to run the tool again.
// Silence here would trade tokens for fabrication, which is not a trade this
// project makes (see the honesty section of the coder prompt).
//
// THREE RULES KEEP IT FROM HANDICAPPING THE CODING WORK:
//
//  1. Locally reproducible tools ONLY. Re-running `view`, `find` or
//     `diagnostics` is cheap, local, and returns today's truth. `fetch` and
//     `websearch` are read-only too but are NOT reproducible: the network may
//     be gone, the page may have changed, and re-fetching costs the user real
//     bandwidth on a metered link. They are never evicted. bash/edit/write/patch
//     are excluded for the same reason supersede.go excludes them: their output
//     is side-effectful and cannot be regenerated by repeating the call.
//
//  2. A generous recency window. Nothing within evictAfterAssistantTurns of the
//     end is touched, so the model's recent working context is never disturbed.
//     THIS, not any per-file rule, is what protects the working set: a file the
//     model is actually working on gets read, edited or referenced inside the
//     window, and anything inside the window is untouchable.
//
//  3. Errors are never evicted, and neither is anything already small. An error
//     is usually the thing being worked on, and stubbing a 200-byte result to
//     save 40 bytes is churn.
//
// A RULE THAT WAS TRIED AND REMOVED, because it is the obvious idea and it does
// not work: "always keep the newest result for each distinct call key". It reads
// as a safety rule and it is really an off switch. A file read ONCE is trivially
// the newest read of itself, so under that rule it can never be evicted, and a
// read-once-then-idle result is EXACTLY the case this function exists for. With
// it in place, age eviction collapses into supersede.go and does nothing new.
// Caught by TestAnIdleReadIsDroppedWithAStubThatSaysSo failing on the first run,
// 2026-08-23. The generalisation is worth more than the rule: a guard that makes
// a feature safe by making it inert is not a safe feature, it is a disabled one,
// and it will pass every test that does not assert the feature actually fires.
//
// Nothing is deleted from the session store. This shapes only what goes on the
// wire; the full transcript stays on disk and greppable, which is the
// never-delete rule holding.

// ageEvictableTools are read-only AND locally reproducible: running them again
// costs a local call and returns current truth rather than a stale snapshot.
//
// NOTE what is deliberately absent: fetch and websearch. They are read-only but
// re-running them hits the network, which on this project's target connection
// (single-digit KB/s, metered) is a real cost imposed on the user, and may
// return something different or nothing at all. Evicting a page the model
// already paid to download would be a false economy.
var ageEvictableTools = map[string]bool{
	"view":        true,
	"find":        true,
	"diagnostics": true,
}

// evictAfterAssistantTurns is how many assistant turns must have happened AFTER
// a result before it is considered idle.
//
// Eight rather than two or three, deliberately. The cost of being wrong is
// asymmetric: evicting too eagerly forces a re-read and risks the model
// answering from memory, while evicting too late merely costs tokens. Eight
// assistant turns is well past the point where a result is part of the active
// working set: anything the model is genuinely still using gets read, edited or
// referenced again inside that window, which resets nothing but does mean the
// live copy sits inside the protected zone.
const evictAfterAssistantTurns = 8

// evictAgeMinContent matches supersede.go: below this the stub saves nothing.
const evictAgeMinContent = 400

const agedStubFmt = "[dropped to save context: this %s result is %d turns old and " +
	"has not been needed since. The content is NOT lost, it is in the session store " +
	"on disk. If you still need it, run %s again rather than recalling it from " +
	"memory: the file may have changed since.]"

// evictAgedReads returns a view of messages in which idle, locally reproducible
// tool results have had their Content replaced by a stub that says so.
//
// The input slice and the stored message Parts are never mutated: only messages
// that actually change are rebuilt with a fresh Parts slice, matching
// supersedeStaleReads.
func evictAgedReads(messages []message.Message) []message.Message {
	// Which tool_call ids belong to an evictable tool. Unlike supersede.go this
	// needs no argument keying: age alone decides, so the id set is enough.
	callKey := make(map[string]bool)
	for mi := range messages {
		for _, tc := range messages[mi].ToolCalls() {
			if ageEvictableTools[tc.Name] {
				callKey[tc.ID] = true
			}
		}
	}
	if len(callKey) == 0 {
		return messages
	}

	// assistantTurnsAfter[i] is how many assistant messages appear after index i.
	// Counted from the end in one pass so the whole function stays linear.
	assistantTurnsAfter := make([]int, len(messages))
	seen := 0
	for i := len(messages) - 1; i >= 0; i-- {
		assistantTurnsAfter[i] = seen
		if messages[i].Role == message.Assistant {
			seen++
		}
	}

	out := make([]message.Message, len(messages))
	copy(out, messages)
	for mi := range out {
		age := assistantTurnsAfter[mi]
		if age < evictAfterAssistantTurns {
			continue // rule 2: recent working context is never touched
		}
		var cloned []message.ContentPart
		for pi, part := range out[mi].Parts {
			tr, ok := part.(message.ToolResult)
			if !ok {
				continue
			}
			// rule 1 (an evictable tool) and rule 3 (errors, small results).
			if !callKey[tr.ToolCallID] || tr.IsError || len(tr.Content) < evictAgeMinContent {
				continue
			}
			if cloned == nil {
				cloned = make([]message.ContentPart, len(out[mi].Parts))
				copy(cloned, out[mi].Parts)
			}
			tr.Content = fmt.Sprintf(agedStubFmt, tr.Name, age, tr.Name)
			cloned[pi] = tr
		}
		if cloned != nil {
			out[mi].Parts = cloned
		}
	}
	return out
}
