package export

// GORILLA OVERRIDE (2026-08-18): the handoff brief — how work that stopped gets
// picked up again, by this model or by a different one.
//
// WHY REOPENING IS NOT ENOUGH. /sessions can reopen a past conversation, and for
// a short one that is the right answer: every message goes back into context and
// the model carries on. But a real working session on this machine measured 275
// messages and 2.6 MB. Reloading that into a 32K model does not resume the work,
// it reproduces the exact failure that killed the research run on 2026-08-17 —
// context over the window, at the moment the model is asked to do the hardest
// part. The bigger the session, the more certainly reopening it fails, which is
// backwards.
//
// So this does what /osint --recover does for research, for ordinary work: it
// distils the session in PURE GO — no tokens, no model, nothing that can fail
// the same way — and starts a fresh conversation carrying only the distillate.
//
// WHAT A BRIEF MUST CONTAIN, and the order is deliberate:
//
//   1. THE GOAL — every instruction the user gave, verbatim. These are the most
//      valuable bytes in the session and the cheapest: corrections especially,
//      because they record where the previous attempt went wrong.
//   2. WHAT WAS DONE — files written, commands run, counted and deduplicated.
//   3. WHAT FAILED — every tool error and abnormal ending. A brief that lists
//      only successes invites the next model to assume the rest worked.
//   4. WHERE IT STOPPED — the last thing said, so the seam is visible.
//   5. WHAT IS NOT KNOWN — stated outright. This is reconstructed from stored
//      messages; it cannot tell whether any of it was verified, and a model that
//      assumes otherwise will build on sand.
//
// The last section is the one that makes this safe to hand to a DIFFERENT model.
// A brief that reads as settled fact turns "someone else was working on this"
// into "this is done", and that is how a half-finished change gets committed.

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/opencode-ai/opencode/internal/message"
	"github.com/opencode-ai/opencode/internal/session"
)

// HandoffStats is what the brief covered, so the caller can report honestly
// rather than claiming the whole session travelled.
type HandoffStats struct {
	Messages     int
	Instructions int
	FilesTouched int
	Commands     int
	Failures     int
	Truncated    bool // some content was dropped to fit the budget
	Chars        int
}

// EstimatedTokens uses the same rough four-characters-per-token convention as
// the rest of this program. Crude on purpose: it decides whether to warn.
func (s HandoffStats) EstimatedTokens() int { return s.Chars / 4 }

// Handoff builds the brief. budgetChars bounds the result; 0 means unbounded.
//
// Nothing here calls a model. That is the point: a resume that needed an LLM to
// work out what had happened would be a second chance to fail at exactly the
// step that already failed.
func Handoff(sess session.Session, msgs []message.Message, branches []Branch, budgetChars int) (string, HandoffStats) {
	ordered := make([]message.Message, len(msgs))
	copy(ordered, msgs)
	sort.SliceStable(ordered, func(i, j int) bool { return ordered[i].CreatedAt < ordered[j].CreatedAt })

	var (
		instructions []string
		files        = map[string]int{}
		commands     []string
		failures     []string
		models       = map[string]bool{}
		lastSaid     string
	)

	for _, m := range ordered {
		switch m.Role {
		case message.User:
			if t := strings.TrimSpace(m.Content().String()); t != "" {
				instructions = append(instructions, t)
			}
		case message.Assistant:
			if m.Model != "" {
				models[string(m.Model)] = true
			}
			if t := strings.TrimSpace(m.Content().String()); t != "" {
				lastSaid = t
			}
			for _, tc := range m.ToolCalls() {
				switch tc.Name {
				case "write", "edit", "patch":
					if p := pathFrom(tc.Input); p != "" {
						files[p]++
					}
				case "bash":
					if c := fieldFrom(tc.Input, "command"); c != "" {
						commands = append(commands, c)
					}
				}
			}
			if fr := string(m.FinishReason()); isAbnormal(m.FinishReason()) {
				failures = append(failures, "the turn ended abnormally: "+fr)
			}
		case message.Tool:
			for _, tr := range m.ToolResults() {
				if tr.IsError {
					name := tr.Name
					if name == "" {
						name = "a tool"
					}
					failures = append(failures, name+" failed: "+firstLine(tr.Content))
				}
			}
		}
	}

	// Helper sessions contribute what they DID and what FAILED, but never
	// instructions: a helper's prompt is generated by this program, not written
	// by the user, and treating it as an instruction would put machine-authored
	// text at the top of the brief as though the user had asked for it.
	//
	// They are included at all because a research run's work happens in the
	// lanes. A brief built from the orchestrator's dozen messages describes the
	// wrapper, not the job.
	helperMsgs := 0
	for _, br := range branches {
		for _, m := range br.Messages {
			helperMsgs++
			switch m.Role {
			case message.Assistant:
				for _, tc := range m.ToolCalls() {
					switch tc.Name {
					case "write", "edit", "patch":
						if p := pathFrom(tc.Input); p != "" {
							files[p]++
						}
					case "bash":
						if c := fieldFrom(tc.Input, "command"); c != "" {
							commands = append(commands, c)
						}
					}
				}
			case message.Tool:
				for _, tr := range m.ToolResults() {
					if tr.IsError {
						name := tr.Name
						if name == "" {
							name = "a tool"
						}
						failures = append(failures,
							"in helper \""+strings.TrimSpace(br.Session.Title)+"\": "+name+" failed: "+firstLine(tr.Content))
					}
				}
			}
		}
	}

	stats := HandoffStats{
		Messages:     len(ordered) + helperMsgs,
		Instructions: len(instructions),
		FilesTouched: len(files),
		Commands:     len(commands),
		Failures:     len(failures),
	}

	var b strings.Builder

	b.WriteString("You are picking up work that stopped part-way. This is a reconstruction of " +
		"what happened, built from the stored record of that session — not a memory, and not " +
		"a claim that any of it is correct.\n\n")
	fmt.Fprintf(&b, "SESSION: %q\n", strings.TrimSpace(sess.Title))
	if len(ordered) > 0 {
		fmt.Fprintf(&b, "RAN: %s → %s\n",
			at(ordered[0].CreatedAt).Format("2006-01-02 15:04"),
			at(ordered[len(ordered)-1].CreatedAt).Format("2006-01-02 15:04"))
	}
	if len(models) > 0 {
		fmt.Fprintf(&b, "WORKED ON BY: %s\n", strings.Join(sortedKeys(models), ", "))
	}
	if len(branches) > 0 {
		fmt.Fprintf(&b, "MESSAGES IN THE ORIGINAL: %d, across the conversation and %d helper sessions\n\n",
			len(ordered)+helperMsgs, len(branches))
	} else {
		fmt.Fprintf(&b, "MESSAGES IN THE ORIGINAL: %d\n\n", len(ordered))
	}

	// 1. THE GOAL. Verbatim, and first, because everything else is subordinate
	// to it — and because a paraphrased instruction is how a resumed session
	// quietly starts solving a different problem.
	b.WriteString("## What you were asked to do\n\n")
	b.WriteString("Every instruction from the user, in order, exactly as given. Later ones may " +
		"correct earlier ones — where they conflict, the later instruction wins.\n\n")
	for i, ins := range instructions {
		fmt.Fprintf(&b, "%d. %s\n\n", i+1, clip(ins, 2000))
	}
	if len(instructions) == 0 {
		b.WriteString("(none recorded)\n\n")
	}

	// 2. WHAT WAS DONE.
	b.WriteString("## What the previous attempt did\n\n")
	if len(files) > 0 {
		b.WriteString("Files it wrote to or edited:\n\n")
		for _, p := range sortedKeys(files) {
			fmt.Fprintf(&b, "- `%s` (%d times)\n", p, files[p])
		}
		b.WriteString("\n")
	}
	if len(commands) > 0 {
		fmt.Fprintf(&b, "Commands it ran (%d in total; the last %d):\n\n", len(commands), min(12, len(commands)))
		for _, c := range tail(commands, 12) {
			fmt.Fprintf(&b, "- `%s`\n", clip(oneLine(c), 160))
		}
		b.WriteString("\n")
	}
	if len(files) == 0 && len(commands) == 0 {
		b.WriteString("No files were changed and no commands were run — the session had not " +
			"reached the point of doing anything yet.\n\n")
	}

	// 3. WHAT FAILED. Before "where it stopped", so it is read before the
	// hopeful last paragraph rather than after it.
	b.WriteString("## What went wrong\n\n")
	if len(failures) == 0 {
		b.WriteString("Nothing was recorded as failing. That is not the same as everything " +
			"having worked — it only means no tool reported an error.\n\n")
	} else {
		for _, f := range tail(failures, 15) {
			fmt.Fprintf(&b, "- %s\n", clip(oneLine(f), 200))
		}
		if len(failures) > 15 {
			fmt.Fprintf(&b, "- ...and %d earlier failures\n", len(failures)-15)
		}
		b.WriteString("\n")
	}

	// 4. WHERE IT STOPPED.
	b.WriteString("## Where it stopped\n\n")
	if lastSaid == "" {
		b.WriteString("The session ended without the assistant saying anything — it was cut off " +
			"mid-turn. Assume nothing about the last thing it was doing.\n\n")
	} else {
		fmt.Fprintf(&b, "The last thing it said:\n\n> %s\n\n", clip(oneLine(lastSaid), 1500))
	}

	// 5. WHAT IS NOT KNOWN. Load-bearing, especially across models.
	b.WriteString("## What this brief does NOT tell you\n\n")
	b.WriteString("- Whether any of the work above is **correct**. Nothing here was verified; " +
		"a file being written is not the file being right.\n")
	b.WriteString("- Whether the work is **finished**. A session can stop because it was done, " +
		"because the power went, or because it hit a wall. The record does not say which.\n")
	b.WriteString("- Anything that was decided but never written down or acted on.\n")
	b.WriteString("- The reasoning behind the choices — the previous attempt's thinking is not " +
		"carried across, only what it actually did.\n\n")

	b.WriteString("## What to do now\n\n")
	b.WriteString("1. Say in three or four lines what you understand the task to be and what you " +
		"think the current state is. State it as your reading, not as fact. Do not ask the user " +
		"to confirm before starting — say what you are assuming and go.\n")
	b.WriteString("2. **Check before you redo.** Look at the files listed above as they are now, " +
		"rather than assuming the previous attempt either succeeded or failed.\n")
	b.WriteString("3. Then continue the work.\n")

	out := b.String()
	if budgetChars > 0 && len(out) > budgetChars {
		out = trimToBudget(out, budgetChars)
		stats.Truncated = true
	}
	stats.Chars = len(out)
	return out, stats
}

// trimToBudget cuts from the MIDDLE — the "what it did" detail — and never from
// the instructions at the top or the guidance at the bottom, because those are
// the two parts that decide whether the next model does the right thing.
func trimToBudget(s string, budget int) string {
	const marker = "## Where it stopped"
	head, tail, ok := strings.Cut(s, marker)
	if !ok || len(tail) >= budget {
		// Nothing structured to cut, or the tail alone blows the budget: keep
		// the head, which holds the instructions.
		return clip(s, budget) + "\n\n[TRUNCATED to fit the model's context — the full session is still stored.]\n"
	}
	room := budget - len(tail) - len(marker) - 120
	if room < 0 {
		room = 0
	}
	return clip(head, room) +
		"\n\n[Some detail of what the previous attempt did was dropped to fit this model's " +
		"context. The full session is still stored and can be exported in /sessions.]\n\n" +
		marker + tail
}

// pathFrom pulls a file path out of a tool call's JSON input, accepting the two
// spellings the tools in this program use.
func pathFrom(input string) string {
	for _, k := range []string{"file_path", "path"} {
		if v := fieldFrom(input, k); v != "" {
			return v
		}
	}
	return ""
}

func fieldFrom(input, key string) string {
	var m map[string]any
	if err := json.Unmarshal([]byte(input), &m); err != nil {
		return ""
	}
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func tail[T any](s []T, n int) []T {
	if len(s) <= n {
		return s
	}
	return s[len(s)-n:]
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

func firstLine(s string) string {
	line, _, _ := strings.Cut(strings.TrimSpace(s), "\n")
	return line
}

func clip(s string, n int) string {
	if n <= 0 {
		return ""
	}
	if r := []rune(s); len(r) > n {
		return string(r[:n]) + "..."
	}
	return s
}

// at is defined in transcript.go; declared here only to document that handoff
// shares the same seconds-not-milliseconds reading of stored timestamps.
var _ = func(i int64) time.Time { return at(i) }
