package db

// GORILLA OVERRIDE: this file is hand-written and deliberately NOT generated by
// sqlc, so a regeneration cannot silently drop it. It answers one question the
// generated queries cannot: what did a conversation cost INCLUDING the helper
// sessions spawned underneath it?
//
// WHY IT EXISTS. Research helpers each run in their own task session, so their
// token usage lives in their own rows and never appeared in the number the user
// watches. A first attempt ADDED helper tokens into the parent row — and it was
// wiped within seconds, every time, because internal/llm/agent assigns those
// fields (`sess.PromptTokens = usage.InputTokens`, not `+=`) at the end of each
// turn. Observed live: a run rolled up to 522,261 tokens and the next assistant
// turn overwrote it with 44,688.
//
// So the total is COMPUTED, never stored: nothing writes it, therefore nothing
// can clobber it, and it is correct retroactively for runs that already exist.

import "context"

const sumSessionTokens = `
SELECT
  COALESCE(SUM(prompt_tokens), 0),
  COALESCE(SUM(completion_tokens), 0)
FROM sessions
WHERE id = ?1 OR parent_session_id = ?1
`

// SumSessionTokens totals a conversation and every task session spawned from
// it. One level deep is enough: helper sessions are created with the
// conversation as their parent, and supervisors likewise.
func (q *Queries) SumSessionTokens(ctx context.Context, sessionID string) (prompt, completion int64, err error) {
	row := q.db.QueryRowContext(ctx, sumSessionTokens, sessionID)
	err = row.Scan(&prompt, &completion)
	return prompt, completion, err
}
