package db

// GORILLA OVERRIDE (2026-08-18): hand-written, deliberately not generated by
// sqlc, for the same reason as helper_totals.go — a regeneration cannot
// silently drop it.
//
// WHY IT EXISTS. `ListSessions` filters to `parent_session_id IS NULL`, and
// correctly so: the session picker must show conversations, not the ten helper
// sessions a single research run spawns underneath one. But that filter is
// exactly what `/osint --recover` needs to look past — the findings of a run
// whose write-up died live in those child rows and nowhere else.
//
// Found by writing the recovery path against ListSessions and getting zero runs
// from a store that demonstrably held four. The query was doing its job; it was
// the wrong query for this question.

import "context"

const listResearchHelpers = `
SELECT id, title, prompt_tokens, completion_tokens, created_at
FROM sessions
WHERE parent_session_id IS NOT NULL AND title LIKE 'Research: %'
ORDER BY created_at DESC
`

// ResearchHelper is one helper session, carrying only what recovery needs. The
// full row is not fetched: a listing that reads every column of every lane of
// every run gets slower with every run the user ever made.
type ResearchHelper struct {
	ID               string
	Title            string
	PromptTokens     int64
	CompletionTokens int64
	CreatedAt        int64
}

// ListResearchHelpers returns every research helper session, newest first.
func (q *Queries) ListResearchHelpers(ctx context.Context) ([]ResearchHelper, error) {
	rows, err := q.db.QueryContext(ctx, listResearchHelpers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []ResearchHelper
	for rows.Next() {
		var h ResearchHelper
		if err := rows.Scan(&h.ID, &h.Title, &h.PromptTokens, &h.CompletionTokens, &h.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, h)
	}
	return out, rows.Err()
}

const listChildSessions = `
SELECT id, title, prompt_tokens, completion_tokens, created_at
FROM sessions
WHERE parent_session_id = ?1
ORDER BY created_at
`

// ListChildSessions returns every session spawned from one conversation —
// research lanes, supervisors, summarisers.
//
// GORILLA (2026-08-18): added when the sessions manager exported a run as "14
// messages" while listing it as 275. The other 261 were in the helper sessions,
// and they are where the reasoning and tool calls live — the material the
// export exists to preserve. An export that silently drops 95% of a run is
// worse than no export, because it looks complete.
func (q *Queries) ListChildSessions(ctx context.Context, parentID string) ([]ResearchHelper, error) {
	rows, err := q.db.QueryContext(ctx, listChildSessions, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []ResearchHelper
	for rows.Next() {
		var h ResearchHelper
		if err := rows.Scan(&h.ID, &h.Title, &h.PromptTokens, &h.CompletionTokens, &h.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, h)
	}
	return out, rows.Err()
}
