package db

// GORILLA OVERRIDE (2026-08-18): hand-written, deliberately not generated by
// sqlc, so a regeneration cannot silently drop it. Same reason as
// helper_totals.go and research_helpers.go.
//
// WHY IT EXISTS — the owner's framing, and it decides every choice in this file:
//
//   "these laptops will have very, very limited space... early Chromebooks or
//    devices from before Chromebooks, Raw SLC NAND, CompactFlash, PATA Flash,
//    eMMC, where they'd be lucky to have 1 to 2 GB of available storage. For
//    them we need the ability to fully delete, erase and purge past sessions,
//    as the current architecture doesn't seem to care about the kids — the data
//    just gets accumulated and stored with no concern for storage management."
//
// Measured on the developer's own store, 2026-08-18: 65 sessions, 578 messages,
// 4.77 MB of message parts, a 5.4 MB database and a 4.3 MB write-ahead log that
// nothing ever truncated. Nearly 10 MB, none of it visible or removable from
// inside the program.
//
// THREE THINGS THAT ARE EASY TO GET WRONG HERE, and all three are why this file
// is hand-written rather than four generated one-liners:
//
//  1. DELETE DOES NOT FREE SPACE. SQLite marks pages free and reuses them
//     later; the FILE does not shrink. On a device with 1 GB free, an "erase"
//     that reclaims nothing is not an erase. VACUUM is what returns the bytes,
//     and it needs room to work, so it is a separate, explicit step.
//
//  2. THE WRITE-AHEAD LOG IS NOT THE DATABASE. It was 4.3 MB — 44% of the total
//     — and a VACUUM alone leaves it. It has to be checkpointed and truncated.
//
//  3. HELPER SESSIONS ARE NOT CHILDREN AS FAR AS SQLite IS CONCERNED. Messages
//     have a foreign key to their session and cascade correctly. Sessions do
//     NOT have one on parent_session_id, so deleting a conversation leaves
//     every helper session it spawned behind — and a single supervised research
//     run spawns seventeen. Deleting must walk that relationship explicitly.

import (
	"context"
	"fmt"
)

// SessionStorage is what one session occupies, and what it holds.
type SessionStorage struct {
	SessionID string
	Bytes     int64 // message parts + stored file contents, for this session and its helpers
	Messages  int64
	Helpers   int64
}

const sessionStorageQuery = `
SELECT
  COALESCE((SELECT SUM(LENGTH(m.parts)) FROM messages m
            WHERE m.session_id = ?1 OR m.session_id IN
              (SELECT id FROM sessions WHERE parent_session_id = ?1)), 0),
  COALESCE((SELECT SUM(LENGTH(f.content)) FROM files f
            WHERE f.session_id = ?1 OR f.session_id IN
              (SELECT id FROM sessions WHERE parent_session_id = ?1)), 0),
  COALESCE((SELECT COUNT(*) FROM messages m
            WHERE m.session_id = ?1 OR m.session_id IN
              (SELECT id FROM sessions WHERE parent_session_id = ?1)), 0),
  COALESCE((SELECT COUNT(*) FROM sessions WHERE parent_session_id = ?1), 0)
`

// SessionStorageFor reports what a conversation costs on disk INCLUDING the
// helper sessions spawned underneath it. A research run's ten helpers hold the
// bulk of its bytes; attributing them to the parent is the only number that
// answers "what do I get back if I delete this?".
func (q *Queries) SessionStorageFor(ctx context.Context, sessionID string) (SessionStorage, error) {
	var s SessionStorage
	var partBytes, fileBytes int64
	err := q.db.QueryRowContext(ctx, sessionStorageQuery, sessionID).
		Scan(&partBytes, &fileBytes, &s.Messages, &s.Helpers)
	s.SessionID = sessionID
	s.Bytes = partBytes + fileBytes
	return s, err
}

const allSessionStorageQuery = `
SELECT s.id,
       COALESCE(SUM(LENGTH(m.parts)), 0),
       COUNT(m.id)
FROM sessions s
LEFT JOIN messages m
  ON m.session_id = s.id
  OR m.session_id IN (SELECT id FROM sessions WHERE parent_session_id = s.id)
WHERE s.parent_session_id IS NULL
GROUP BY s.id
`

// AllSessionStorage returns the same figure for every conversation in one
// query. The list view needs a size per row, and asking per row turns opening a
// screen into one query per session — which on a slow eMMC is felt.
func (q *Queries) AllSessionStorage(ctx context.Context) (map[string]SessionStorage, error) {
	rows, err := q.db.QueryContext(ctx, allSessionStorageQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := map[string]SessionStorage{}
	for rows.Next() {
		var s SessionStorage
		if err := rows.Scan(&s.SessionID, &s.Bytes, &s.Messages); err != nil {
			return nil, err
		}
		out[s.SessionID] = s
	}
	return out, rows.Err()
}

// StoreTotals is the whole picture, for the header of the manager screen.
type StoreTotals struct {
	Sessions int64
	Helpers  int64
	Messages int64
	Bytes    int64 // live content: message parts plus stored file contents
}

const storeTotalsQuery = `
SELECT
  (SELECT COUNT(*) FROM sessions WHERE parent_session_id IS NULL),
  (SELECT COUNT(*) FROM sessions WHERE parent_session_id IS NOT NULL),
  (SELECT COUNT(*) FROM messages),
  (SELECT COALESCE(SUM(LENGTH(parts)), 0) FROM messages)
    + (SELECT COALESCE(SUM(LENGTH(content)), 0) FROM files)
`

func (q *Queries) StoreTotals(ctx context.Context) (StoreTotals, error) {
	var t StoreTotals
	err := q.db.QueryRowContext(ctx, storeTotalsQuery).
		Scan(&t.Sessions, &t.Helpers, &t.Messages, &t.Bytes)
	return t, err
}

// DeleteSessionTree removes a conversation, every helper session spawned from
// it, and all their messages and stored files.
//
// The helper sessions must be named explicitly: sessions have no foreign key on
// parent_session_id, so the database will not remove them and a supervised
// research run leaves seventeen orphans behind. Messages and files DO cascade
// from their own session, so deleting the session rows is enough for those.
//
// Returns how many session rows went, so the caller can tell the user what
// actually happened rather than assuming.
func (q *Queries) DeleteSessionTree(ctx context.Context, sessionID string) (int64, error) {
	// The DBTX interface this package is generated against exposes Exec and
	// Query, not transactions, so the two statements run separately. The ORDER
	// is what makes that safe: helpers first, parent second. An interruption
	// between them leaves the helper rows gone and the parent still listed —
	// visible, and deletable again. The reverse order would leave a deleted
	// parent with orphaned helpers, which is the state that hides bytes forever
	// because nothing in the interface can still name them.
	res, err := q.db.ExecContext(ctx,
		`DELETE FROM sessions WHERE parent_session_id = ?1`, sessionID)
	if err != nil {
		return 0, fmt.Errorf("removing helper sessions: %w", err)
	}
	removed, _ := res.RowsAffected()

	res, err = q.db.ExecContext(ctx, `DELETE FROM sessions WHERE id = ?1`, sessionID)
	if err != nil {
		return removed, fmt.Errorf("removing the session: %w", err)
	}
	n, _ := res.RowsAffected()
	return removed + n, nil
}

// Reclaim actually returns the freed bytes to the filesystem.
//
// Called after deleting, never instead of it. VACUUM rewrites the database
// without its free pages; the WAL checkpoint then truncates the write-ahead
// log, which on the developer's machine held 4.3 MB of the 9.8 MB total and
// which VACUUM alone does not touch.
//
// VACUUM needs temporary room roughly the size of the database. On a device
// with almost nothing free that can fail — so the error is returned rather than
// swallowed, and the caller says so plainly instead of reporting a reclaim that
// did not happen.
func (q *Queries) Reclaim(ctx context.Context) error {
	if _, err := q.db.ExecContext(ctx, `VACUUM`); err != nil {
		return fmt.Errorf("VACUUM failed, so the space was not returned to the disk: %w", err)
	}
	if _, err := q.db.ExecContext(ctx, `PRAGMA wal_checkpoint(TRUNCATE)`); err != nil {
		return fmt.Errorf("the database shrank but the write-ahead log could not be truncated: %w", err)
	}
	return nil
}

const searchSessionsQuery = `
SELECT DISTINCT s.id
FROM sessions s
LEFT JOIN messages m ON m.session_id = s.id
WHERE s.parent_session_id IS NULL
  AND (LOWER(s.title) LIKE ?1 OR LOWER(m.parts) LIKE ?1)
`

// SearchSessions returns the ids of conversations whose title OR message
// content matches.
//
// Content and not just title, because titles are generated from the first
// message and are frequently useless for finding a session weeks later — "New
// Session" is a real title this program writes. Someone looking for the run
// where they discussed a particular error is searching for the error, not for
// whatever the summariser called the day.
//
// LIKE with a lowercased needle rather than FTS: adding a full-text index would
// mean a second copy of every message on a device that has 1 GB free. On this
// store — 578 messages, 4.77 MB — a scan is imperceptible, and it stays honest
// as the store grows because the store growing is the thing the user is being
// given tools to prevent.
func (q *Queries) SearchSessions(ctx context.Context, needle string) (map[string]bool, error) {
	rows, err := q.db.QueryContext(ctx, searchSessionsQuery, "%"+needle+"%")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := map[string]bool{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out[id] = true
	}
	return out, rows.Err()
}
